language: ruby
rvm:
- 2.5.1
before_install:
- openssl aes-256-cbc -K $encrypted_e5cde1f85b15_key -iv $encrypted_e5cde1f85b15_iv
  -in github_deploy_key.enc -out ../github_deploy_key -d
  -in _script/github_deploy_key.enc -out github_deploy_key -d
before_script:
- chmod +x ./_script/cibuild
- chmod +x ./_script/deploy
script: "./_script/cibuild"
after_script:
- |
  $(npm bin)/set-up-ssh --key "$encrypted_e5cde1f85b15_key" \
                        --iv "$encrypted_e5cde1f85b15_iv" \
                        --path-encrypted-key "._script/github_deploy_key.enc"
branches:
  only:
  - master
  - gh-pages
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
