language: ruby
rvm:
- 2.5.1
before_install:
  - openssl aes-256-cbc -K $encrypted_f1b2b8e787cf_key -iv $encrypted_f1b2b8e787cf_iv -in _script/github_deploy_key.enc -out ./github_deploy_key -d
  - chmod 600 ./github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add ./github_deploy_key
before_script:
- chmod +x ./_script/cibuild
- chmod +x ./_script/deploy
script: ./_script/cibuild
after_script: ./_script/deploy
branches:
  only:
  - master
  - gh-pages
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
