language: ruby
rvm:
- 2.5.1
before_script:
- chmod +x ./_script/cibuild
- chmod +x ./_script/deploy
script: "./_script/cibuild"
branches:
  only:
  - master
  - gh-pages
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
