language: ruby
rvm:
- 2.5.1
before_script:
- chmod +x ./_script/cibuild
- chmod +x ./_script/deploy
script: "./_script/cibuild"
after_script:
- |
  $(npm bin)/set-up-ssh --key "$encrypted_f1b2b8e787cf_key" \
                        --iv "$encrypted_f1b2b8e787cf_iv" \
                        --path-encrypted-key "./_script/github_deploy_key.enc"
- ./_script/deploy
branches:
  only:
  - master
  - gh-pages
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
