language: ruby
rvm:
  - 2.5.1

before_install:
  - openssl aes-256-cbc -K $encrypted_f37e748a9cc1_key -iv $encrypted_f37e748a9cc1_iv -in _script/github_deploy_key.enc -out github_deploy_key -d

before_script:
  - chmod +x ./_script/cibuild
  - chmod +x ./_script/deploy

script: ./_script/cibuild

after_script:
  - |
    $(npm bin)/set-up-ssh --key "$encrypted_f37e748a9cc1_key" \
                          --iv "$encrypted_f37e748a9cc1_iv" \
                          --path-encrypted-key "._script/github_deploy_key.enc"
#  - ./_script/deploy

# branch whitelist, only for GitHub Pages
branches:
  only:
    - master       # test the master branch
    - gh-pages     # test the gh-pages branch
    - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
    # speeds up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

# uses faster container-based infrastructure
sudo: false

# update SSL certificates
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
