# Metadata
title: "./backlog: Charlie's blog"
author: "Charles Newey"
github_username: "charlienewey"
email: "charlie.newey@gmail.com"
url: "https://charlienewey.github.io"
baseurl: ""
description: >-
    meanderings through interesting tidbits of mathsy computery stuff
comments: true

# Build settings
permalink: /:slug/  # default is: /:year/:month/:day/:slug/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: :compressed
plugins:
  - jekyll-katex     # Maths rendering
  - jekyll-feed      # Create an Atom feed
  - jekyll-seo-tag   # SEO tags
  - jekyll-sitemap   # Create a sitemap
paginate: 10
paginate_path: "/page/:num/"

katex:
  rendering_options:
    throw_error: true
    error_color: "#cc0000"

# Exclude from processing (these are excluded by default).
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
