#! /usr/bin/env bash

set -e

bundle exec jekyll build
bundle exec htmlproofer --url-ignore "/#respond/" \
                        --check-html \
                        --check-opengraph \
                        ./_site
